# R code to plot the time serise and the cdf 
# please run the "usgs data access.R" code first
# 
# Input:
# daily_discharge.Rdat, available_sites.Rdat 
# (these two files are generated by running "usgs data access.R")
# 
# Output:
# discharge_quantiles.Rdat
# time series plot for each site 
# cdf plot for each site 

# load data 
load('daily_discharge.Rdat')
load('available_sites.Rdat')

# get the discharge of the site
discharge_quantiles <- data.frame()

for (i in seq(nrow(available_sites))) {
  
  # get siteID and disturbance date and site discharge
  site_id <- as.character(available_sites[i,1])
  dis_date <- available_sites[i,4]
  before_date <- available_sites[i,2]
  after_date <- available_sites[i,3]
  
  # get site discharge and plot time series as .jpg file
  site_discharge <- subset(daily_discharge,((siteID==site_id)&(Date>=before_date)&(Date<=after_date)),select = c(siteID,Date,Q,LogQ))
  jpeg(paste('ts',site_id,'-',as.character(dis_date),'.jpg')) 
  plot(x=site_discharge[['Date']], y = site_discharge[['Q']],type='l', col='blue', xlab='DateTime', ylab='Daily Discharge (cms)',
      main=paste('Daily Discharge for Site from',as.character(before_date),'to',as.character(after_date),'at', site_id))   
  dev.off()  
  
  
  # calculate the quantile value for before and after disturbance
  aft_dis_discharge <- subset(site_discharge, ((Date>dis_date)&(Date<=after_date)))
  bef_dis_discharge <- subset(site_discharge, ((Date>=before_date)&(Date<=dis_date)))
  my_quantiles=c(0.25,0.5,0.75) # settings for quantile, remember to change new_site_quantiles dataframe below
  bef_quantiles <- as.vector(quantile(bef_dis_discharge[['LogQ']],probs=my_quantiles))
  aft_quantiles <- as.vector(quantile(aft_dis_discharge[['LogQ']],probs=my_quantiles))
  new_site_quantiles = data.frame(siteID=site_id,disDate=dis_date, 
                                  bef_0.25=bef_quantiles[1], bef_0.50=bef_quantiles[2],bef_0.75=bef_quantiles[3],
                                  aft_0.25=aft_quantiles[1], aft_0.50=aft_quantiles[2],aft_0.75=aft_quantiles[3]) 
  discharge_quantiles = rbind(discharge_quantiles,new_site_quantiles)
    
 
  # plot cdf plot for befor and after disturbance and save as .jpg file
  bef_values = bef_dis_discharge[['LogQ']]
  aft_values = aft_dis_discharge[['LogQ']]
  
  jpeg(paste('cdf',site_id,'-',as.character(dis_date),'.jpg'))  
  plot(x=sort(unique(bef_values)),y=sort(ecdf(bef_values)(unique(bef_values)))*100,type='l',col='red', lwd=3,ylab='cdf(%)',xlab='daily discharge (cms)',
       main = paste('CDF Before and After Disturbance on',as.character(dis_date),'at', site_id))
  points(x=sort(unique(aft_values)),y=sort(ecdf(aft_values)(unique(aft_values)))*100,col='blue',type='l',lwd=3)  
  segments(aft_quantiles[2],0,aft_quantiles[2],50,lty='dotdash')
  segments(bef_quantiles[2],0,bef_quantiles[2],50,lty='dotdash')
  segments(min(bef_values,aft_values),50,max(aft_quantiles[2],bef_quantiles[2]),50,lty='dotdash')  
  legend ('topleft', c('Before Disturbance','After Disturbance'),lty='solid',col=c('red','blue'),bty='n')
  dev.off()
}

save(discharge_quantiles,file="discharge_quantiles.Rdat")

#   site_plot_data = summarize(site_discharge,Flow=unique(LogQ), cdf=ecdf(LogQ)(unique(LogQ)))
#   ggplot(site_plot_data, aes(Flow, cdf)) + geom_step()